<img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 01</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays (Part-02)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [WHAT NUMPY? & WHY DO WE NEED IT?](#0)
    * [When you make a change to an array, it becomes another object.](#0.1)
    * [Advanced mathematical operations are executed more efficientl](#0.2)
    * [Comparing list and array by ids](#0.3)
    * [Comparing list and array by size](#0.4)
    * [Comparing list and array by computation time](#0.5)
* [THE END OF THE SESSION-01 (PART-02)](#1)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Why Numpy? & Why Do We Need It?</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**There are several important differences between NumPy arrays and the standard Python sequences:**

- **``NumPy arrays``** have a ``fixed size`` at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a **``NumPy array``** are all required to be of ``the same data type``, and thus will be the ``same size in memory``. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- **``NumPy arrays``** facilitate ``advanced mathematical and other types of operations`` on large numbers of data. Typically, such operations are executed more efficiently and ``with less code`` than is possible using Python's built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today's scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

<img src=https://i.ibb.co/2FD1VMM/Numpy-vs-Lists.pngg width="500" height="200">

[Numpy Array vs List Source 01](https://blog.finxter.com/what-are-advantages-of-numpy-over-regular-python-lists/),
[Numpy Array vs List Source 02](https://numpy.org/doc/stable/user/whatisnumpy.html),
[Numpy Array vs List Source 03](https://python.plainenglish.io/python-list-vs-numpy-array-whats-the-difference-7308cd4b52f6),
[Numpy vs List Source 04](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.),
[Numpy Array vs List Source 05](https://dev.to/chanduthedev/python-list-vs-numpy-array-3pjp),
[Numpy Array vs List Source 06](https://medium.com/analytics-vidhya/list-vs-numpy-comparision-35bf921588e9),
[Numpy Array vs List Source 07](https://stackoverflow.com/questions/15944171/python-differences-between-lists-and-numpy-array-of-objects),
[Numpy Array vs List Video Source 01](https://www.youtube.com/watch?v=mkbgEvUkSaM),
[Numpy Array vs List Video Source 02](https://www.youtube.com/watch?v=JtW_xGNDEJ8),
[Numpy Array vs List Video Source 03](https://www.youtube.com/watch?v=C10KmAbCW6A)

In [3]:
import numpy as np
import time
import sys

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">When you make a change to an array, it becomes another object!</p>

<a id="0.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [2]:
my_list = [1, 2, 3, 4, 5]

my_first_array = np.array(my_list)
my_first_array

array([1, 2, 3, 4, 5])

In [3]:
id(my_first_array)  # this is the location of my_first_array in memory.

2950143668112

In [4]:
id(np.append(my_first_array, (6, 7)))   # the location of array changed.
                                        # this is a different array object now.

2950164668112

**let's look at the same situation for the lists in Python:**

In [5]:
id(my_list)  # this is the location of my_list in memory.

2950164569344

In [6]:
my_list.append([6, 7])  # we have added some values to the list.
my_list

[1, 2, 3, 4, 5, [6, 7]]

In [7]:
id(my_list)  # Be noted! The location of my_list didn't change.
             # Unlike numpy arrays, it is still the same object!

2950164569344

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Advanced mathematical operations are executed more efficiently</p>

<a id="0.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [1]:
list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]

In [9]:
# a * b # Gives an error # element - wise

In [2]:
list_a + list_b # combines lists

[1, 2, 3, 4, 2, 3, 4, 5]

In [10]:
a_mult_b = []

for i in range(len(list_a)) :
    a_mult_b.append(list_a[i] * list_b[i])
    
a_mult_b

[2, 6, 12, 20]

**let's do the same in the numpy arrays:**

In [11]:
a_arr = np.array(list_a)
b_arr = np.array(list_b)

In [12]:
a_arr * b_arr

array([ 2,  6, 12, 20])

**Another example:**

In [13]:
arr_1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4, 5]])
arr_2 = np.array([[2, 3, 4, 5], [1, 2, 4, 5], [1, 2, 3, 4]])

In [14]:
arr_1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [15]:
arr_2

array([[2, 3, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 3, 4]])

In [16]:
arr_1 * arr_2

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by ids</p>

<a id="0.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [17]:
print(list_a)
id(list_a)

[1, 2, 3, 4]


2950144476864

In [18]:
print(list_b)
id(list_b)

[2, 3, 4, 5]


2950164731968

In [19]:
id(list_a) == id(list_b)

False

In [20]:
list_c = list_a[:]

print(list_a)
print(list_c)

id(list_a) == id(list_c)

[1, 2, 3, 4]
[1, 2, 3, 4]


False

In [21]:
list_c = list_a

id(list_a) == id(list_c)

True

In [22]:
print(list_a)
print(id(list_a))
print(id(list_a[0]))
print(id(list_a[1]))
print(id(list_a[2]))
print(id(list_a[0]) == id(list_a[1]) == id(list_a[2]))

[1, 2, 3, 4]
2950144476864
2950059551024
2950059551056
2950059551088
False


In [23]:
print(arr_1)
print(id(arr_1))
print(id(arr_1[0]))
print(id(arr_1[1]))
print(id(arr_1[2]))
print(id(arr_1[0]) == id(arr_1[1]) == id(arr_1[2]))

[[1 2 3 4]
 [1 2 3 4]
 [2 3 4 5]]
2950164758416
2950164874416
2950164874416
2950164874416
True


### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by size</p>

<a id="0.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [24]:
sys.getsizeof(5)  # Returns the size of object in bytes.

28

In [6]:
sys.getsizeof(99999999)

28

In [26]:
sys.getsizeof("a")

50

In [7]:
sys.getsizeof(0)

28

In [27]:
sys.getsizeof("alidelveli")

59

In [28]:
numbers = range(1000)

print("size of one item in list :", sys.getsizeof(numbers[1]))  # sys.getsizeof() returns the memory size of the object 
print("size of all items in list :", sys.getsizeof(numbers[1]) * len(numbers))

print("---" * 10)

arr = np.arange(1000)

print("size of one item in array :", arr.itemsize)  # itemsize() returns the length of one array element in bytes.
print("size of all items in array :", arr.itemsize * arr.size)

size of one item in list : 28
size of all items in list : 28000
------------------------------
size of one item in array : 4
size of all items in array : 4000


### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by computation time</p>

<a id="0.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [29]:
time.time()  # Return the current time in seconds since the Epoch.
# epoch changes from computer to computer

1671117993.2063384

In [30]:
start = time.time()  # Assigning the current epoch time to the "start" variable
start

1671117993.2216017

In [31]:
# Wait for several seconds and than run this cell. 

time.time() - start  # time difference between two operations

0.014781475067138672

In [3]:
import numpy as np
import time

size = 1000000

items1 = range(size)

items2 = range(size)

a1 = np.arange(size)

a2 = np.arange(size)

start = time.time()

result = [(x+y) for x, y in zip(items1, items2)]
print("python list took : ", (time.time() - start) * 1000)

start = time.time()
result = a1 + a2
print("numpy took :", (time.time()-start) * 1000)

python list took :  191.8327808380127
numpy took : 13.993263244628906


## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of the NumPy Session-01 (Part-02)</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>